# vault-reindex.ps1 — Regenerate _index.yaml from all vault .md files.
# Scans every .md file, parses YAML frontmatter, writes a master catalog.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File .cursor/hooks/vault-reindex.ps1
#   Called automatically by agent-complete.ps1 and vault-bridge-platforms.ps1

. "$PSScriptRoot\vault-resolve.ps1"

$indexPath = Join-Path $VaultPath "_index.yaml"
$timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"

$files = Get-ChildItem -Path $VaultPath -Recurse -Filter "*.md" -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne "_index.yaml" -and $_.Name -ne "_index.md" } |
    Sort-Object LastWriteTime -Descending

$entries = @()

foreach ($file in $files) {
    $relPath = $file.FullName.Substring($VaultPath.Length + 1).Replace("\", "/")
    $raw = Get-Content $file.FullName -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
    if (-not $raw) { continue }

    $title = ""
    $type = ""
    $date = ""
    $topics = @()
    $source = ""
    $ingestionType = ""
    $projectId = ""
    $refreshPolicy = ""
    $refreshAfter = ""
    $expiresAfter = ""

    if ($raw -match '(?s)^---\r?\n(.+?)\r?\n---') {
        $fm = $Matches[1]
        if ($fm -match '(?m)^title:\s*[''"]?(.+?)[''"]?\s*$')          { $title = $Matches[1].Trim('"', "'") }
        if ($fm -match '(?m)^type:\s*(.+)$')                            { $type = $Matches[1].Trim() }
        if ($fm -match '(?m)^date:\s*(.+)$')                            { $date = $Matches[1].Trim() }
        if ($fm -match '(?m)^source:\s*(.+)$')                          { $source = $Matches[1].Trim() }
        if ($fm -match '(?m)^ingestion_type:\s*(.+)$')                  { $ingestionType = $Matches[1].Trim() }
        if ($fm -match '(?m)^project_id:\s*(.+)$')                      { $projectId = $Matches[1].Trim() }
        if ($fm -match '(?m)^refresh_policy:\s*(.+)$')                  { $refreshPolicy = $Matches[1].Trim() }
        if ($fm -match '(?m)^refresh_after:\s*(.+)$')                   { $refreshAfter = $Matches[1].Trim() }
        if ($fm -match '(?m)^expires_after:\s*(.+)$')                   { $expiresAfter = $Matches[1].Trim() }
        # Support both "topics" (preferred) and "tags" (legacy)
        if ($fm -match '(?m)^topics:\s*\[(.+?)\]')                      { $topics = $Matches[1] -split ',\s*' | ForEach-Object { $_.Trim().Trim('"', "'") } }
        elseif ($fm -match '(?m)^tags:\s*\[(.+?)\]')                    { $topics = $Matches[1] -split ',\s*' | ForEach-Object { $_.Trim().Trim('"', "'") } }
    }

    if (-not $title) {
        $firstHeading = ($raw -split "`n" | Where-Object { $_ -match '^#\s+' } | Select-Object -First 1)
        if ($firstHeading) { $title = ($firstHeading -replace '^#+\s*', '').Trim() }
        else { $title = [System.IO.Path]::GetFileNameWithoutExtension($file.Name) }
    }

    if (-not $date) { $date = $file.LastWriteTime.ToString("yyyy-MM-dd") }
    if (-not $ingestionType -and $type) { $ingestionType = $type }

    $topicStr = if ($topics.Count -gt 0) { "[" + ($topics -join ", ") + "]" } else { "[]" }
    $pidStr = if ($projectId -and $projectId -ne "null" -and $projectId -ne "unknown") { $projectId } else { "null" }

    $entry = @"
  - path: $relPath
    title: "$($title -replace '"', '\"')"
    type: $type
    ingestion_type: $ingestionType
    date: $date
    topics: $topicStr
    source: $source
    project_id: $pidStr
"@
    if ($refreshPolicy) { $entry += "`n    refresh_policy: $refreshPolicy" }
    if ($refreshAfter)  { $entry += "`n    refresh_after: $refreshAfter" }
    if ($expiresAfter)  { $entry += "`n    expires_after: $expiresAfter" }
    $entries += $entry
}

$header = @"
# Vault Index — auto-generated by vault-reindex.ps1
# Last updated: $timestamp
# Total notes: $($entries.Count)
#
# Do not edit manually. Regenerate with:
#   powershell -ExecutionPolicy Bypass -File .cursor/hooks/vault-reindex.ps1
notes:
"@

$content = $header + "`n" + ($entries -join "`n")
Set-Content -Path $indexPath -Value $content -Encoding UTF8

Write-Host "Vault index updated: $($entries.Count) notes indexed at $indexPath"
