param(
    [string]$VaultOverride = ""
)

if ($VaultOverride) {
    $VaultPath = $VaultOverride
} else {
    . "$PSScriptRoot\g-hk-vault-resolve.ps1"
}

if (-not (Test-Path $VaultPath)) {
    New-Item -ItemType Directory -Path $VaultPath -Force | Out-Null
}

$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'")
$indexYamlPath = Join-Path $VaultPath "_index.yaml"
$indexMdPath = Join-Path $VaultPath "index.md"

$files = Get-ChildItem -Path $VaultPath -Recurse -Filter "*.md" -ErrorAction SilentlyContinue |
    Where-Object {
        $_.FullName -notmatch "\\.obsidian(\|\\)" -and
        $_.Name -notin @("_index.yaml", "index.md", "log.md", "VAULT_SCHEMA.md")
    } |
    Sort-Object FullName

$entries = @()
foreach ($file in $files) {
    $raw = Get-Content $file.FullName -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
    if (-not $raw) {
        continue
    }

    $relativePath = $file.FullName.Substring($VaultPath.Length).TrimStart('\').Replace('\', '/')
    $title = ""
    $type = ""
    $date = ""
    $tags = @()
    $source = ""
    $ingestionType = ""
    $projectId = "null"
    $refreshPolicy = ""
    $refreshAfter = ""
    $expiresAfter = ""

    if ($raw -match '(?s)^---\r?\n(.+?)\r?\n---') {
        $frontmatter = $Matches[1]
        if ($frontmatter -match '(?m)^title:\s*[''"]?(.+?)[''"]?\s*$') { $title = $Matches[1].Trim('"', "'") }
        if ($frontmatter -match '(?m)^type:\s*(.+)$') { $type = $Matches[1].Trim() }
        if ($frontmatter -match '(?m)^date:\s*(.+)$') { $date = $Matches[1].Trim() }
        if ($frontmatter -match '(?m)^source:\s*(.+)$') { $source = $Matches[1].Trim() }
        if ($frontmatter -match '(?m)^ingestion_type:\s*(.+)$') { $ingestionType = $Matches[1].Trim() }
        if ($frontmatter -match '(?m)^project_id:\s*(.+)$') { $projectId = $Matches[1].Trim() }
        if ($frontmatter -match '(?m)^refresh_policy:\s*(.+)$') { $refreshPolicy = $Matches[1].Trim() }
        if ($frontmatter -match '(?m)^next_refresh:\s*(.+)$') { $refreshAfter = $Matches[1].Trim() }
        if ($frontmatter -match '(?m)^expires_after:\s*(.+)$') { $expiresAfter = $Matches[1].Trim() }
        if ($frontmatter -match '(?m)^tags:\s*\[(.+?)\]') {
            $tags = $Matches[1] -split ',\s*' | ForEach-Object { $_.Trim().Trim('"', "'") }
        }
    }

    if (-not $title) {
        $heading = ($raw -split "`n" | Where-Object { $_ -match '^#\s+' } | Select-Object -First 1)
        if ($heading) {
            $title = ($heading -replace '^#+\s*', '').Trim()
        } else {
            $title = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
        }
    }

    if (-not $date) {
        $date = $file.LastWriteTimeUtc.ToString("yyyy-MM-dd")
    }

    if (-not $ingestionType -and $type) {
        $ingestionType = $type
    }

    $entries += [pscustomobject]@{
        path = $relativePath
        title = $title
        type = $type
        ingestion_type = $ingestionType
        date = $date
        tags = $tags
        source = $source
        project_id = $projectId
        refresh_policy = $refreshPolicy
        next_refresh = $refreshAfter
        expires_after = $expiresAfter
    }
}

$yamlHeader = @(
    "# Vault Index - auto-generated by g-hk-vault-reindex.ps1"
    "# Last updated: $timestamp"
    "# Total notes: $($entries.Count)"
    "notes:"
)

$yamlLines = @()
foreach ($entry in $entries) {
    $tagsString = "[" + (($entry.tags | ForEach-Object { $_ }) -join ", ") + "]"
    $yamlLines += "  - path: $($entry.path)"
    $yamlLines += "    title: `"$($entry.title -replace '"', '\"')`""
    $yamlLines += "    type: $($entry.type)"
    $yamlLines += "    ingestion_type: $($entry.ingestion_type)"
    $yamlLines += "    date: $($entry.date)"
    $yamlLines += "    tags: $tagsString"
    $yamlLines += "    source: $($entry.source)"
    $yamlLines += "    project_id: $($entry.project_id)"
    if ($entry.refresh_policy) { $yamlLines += "    refresh_policy: $($entry.refresh_policy)" }
    if ($entry.next_refresh) { $yamlLines += "    next_refresh: $($entry.next_refresh)" }
    if ($entry.expires_after) { $yamlLines += "    expires_after: $($entry.expires_after)" }
}

Set-Content -Path $indexYamlPath -Value (($yamlHeader + $yamlLines) -join "`r`n") -Encoding UTF8

$typeGroups = $entries | Group-Object type | Sort-Object Name
$recentEntries = $entries | Sort-Object date -Descending | Select-Object -First 10

$indexMd = @()
$indexMd += "# Vault Index"
$indexMd += ""
$indexMd += "Generated: $timestamp"
$indexMd += ""
$indexMd += "## Summary"
$indexMd += ""
$indexMd += "- Total notes: $($entries.Count)"
$indexMd += ""

foreach ($group in $typeGroups) {
    $indexMd += "## $($group.Name)"
    $indexMd += ""
    foreach ($entry in ($group.Group | Sort-Object title)) {
        $indexMd += "- [[${($entry.path -replace '\.md$', '')}|$($entry.title)]]"
    }
    $indexMd += ""
}

$indexMd += "## Recent Updates"
$indexMd += ""
foreach ($entry in $recentEntries) {
    $indexMd += "- $($entry.date) - [[${($entry.path -replace '\.md$', '')}|$($entry.title)]]"
}
$indexMd += ""

Set-Content -Path $indexMdPath -Value ($indexMd -join "`r`n") -Encoding UTF8

Write-Host "Vault index updated at $VaultPath ($($entries.Count) notes)"
